/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#ef5b06",
        "surface-container-lowest": "#FFFFFF",
        "on-primary-fixed": "#370e00",
        "tertiary": "#FFD166",
        "surface-tint": "#ef5b06",
        "surface-container-highest": "#211A16",
        "on-background": "#211A16",
        "on-secondary-fixed": "#211A16",
        "inverse-primary": "#ffb598",
        "on-primary-fixed-variant": "#7e2c00",
        "secondary-fixed": "#00E5FF",
        "inverse-on-surface": "#FFFDF7",
        "tertiary-fixed-dim": "#ffb598",
        "outline": "#211A16",
        "on-tertiary-fixed-variant": "#79300d",
        "on-secondary-fixed-variant": "#211A16",
        "surface-bright": "#FFFDF7",
        "error-dim": "#9f0519",
        "surface": "#FFD166",
        "tertiary-container": "#D9B455",
        "on-tertiary-container": "#211A16",
        "primary-fixed": "#ffdbce",
        "secondary-container": "#00E5FF",
        "on-surface": "#211A16",
        "primary-dim": "#8d3200",
        "secondary": "#00E5FF",
        "inverse-surface": "#211A16",
        "on-primary-container": "#ffffff",
        "surface-container": "#FFD166",
        "on-tertiary-fixed": "#370e00",
        "background": "#FFD166",
        "secondary-fixed-dim": "#00E5FF",
        "on-surface-variant": "#5a4137",
        "on-primary": "#ffffff",
        "surface-container-low": "#FFFDF7",
        "surface-variant": "#FFFDF7",
        "outline-variant": "#D9B455",
        "surface-container-high": "#F8F6f5",
        "on-secondary": "#211A16",
        "tertiary-fixed": "#ffdbce",
        "primary-fixed-dim": "#ffb598",
        "secondary-dim": "#823c00",
        "on-error-container": "#93000a",
        "primary-container": "#ef5b06",
        "on-tertiary": "#211A16",
        "on-secondary-container": "#211A16",
        "tertiary-dim": "#6e4800",
        "error": "#ba1a1a",
        "surface-dim": "#D9B455",
        "on-error": "#ffffff",
        "error-container": "#ffdad6"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Plus Jakarta Sans", "sans-serif"],
        "label": ["Space Grotesk", "sans-serif"],
        "display": ["Lilita One", "cursive"],
        "brand": ["Lilita One", "cursive"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
